### ISSUE TITLE
EXPO_PUBLIC_TEXT_KEY crashes the app if null

### ISSUE THREAD

**Issue by Mgayar-sci** [Youssef-S-Negm/Bubbles#74]
`EXPO_PUBLIC_TEXT_KEY` is used without checking for null.

**Comment by Youssef-S-Negm** [comment]
I solved this issue and I would be honored if the code was reviewed by you.
Changes happened in:
-chats.js file (./db/chats.js)
  -sendMessage function
  -decryptMessage function

-ChatScreen.js (./components/screens/ChatScreen.js)
  -MessageItem functional component

**Comment by Mgayar-sci** [comment]
https://github.com/Youssef-S-Negm/Bubbles/pull/75/files#r1289409138
